GB / Олег Гладкий / https://gb.ru/users/3837199 

Библиотеки Python для Data Science: https://gb.ru/lessons/155328/homework

# Урок 1
## Вычисления с помощью Numpy
### Задание 1-n
Задание массива (2×5) и вычисление среднего значения для каждого столбца

In [1]:
import numpy as np

In [2]:
a = (np.array([[1, 2, 3, 3, 1], [6, 8, 11, 10, 7]])).transpose()

In [3]:
a

array([[ 1,  6],
       [ 2,  8],
       [ 3, 11],
       [ 3, 10],
       [ 1,  7]])

In [4]:
mean_a = a.mean(axis=0)

In [5]:
mean_a

array([2. , 8.4])

### Задание 2-n
Вычисление массива, "отцентрированного" по среднему значению признака (столбца).

In [6]:
a_centered = a - mean_a
a_centered

array([[-1. , -2.4],
       [ 0. , -0.4],
       [ 1. ,  2.6],
       [ 1. ,  1.6],
       [-1. , -1.4]])

### Задание 3-n
Скалярное произведение столбцов массива a_centered. Вычисление ковариации двух признаков (столбцов).

In [7]:
a_centered_sp = (a_centered[:, 0]).dot(a_centered[:, 1])
a_centered_sp

8.0

In [8]:
covar = a_centered_sp / (a_centered.shape[0] - 1)
covar

2.0

### Задание 4-n
Вычисление ковариационной матрицы.

In [9]:
covar_mat = np.cov(a.transpose())
covar_mat

array([[1. , 2. ],
       [2. , 4.3]])

In [10]:
print("Ковариация признаков: {}".format(covar_mat[1, 0]))

Ковариация признаков: 2.0


## Вычисления с помощью Pundas



### Задание 1-p
Создание датафрейма book

In [11]:
import pandas as pd