GB / Олег Гладкий / https://gb.ru/users/3837199 

Библиотеки Python для Data Science: https://gb.ru/lessons/155328/homework

# Урок 1
## Вычисления с помощью Numpy
### Задание 1-n
Задание массива (2×5) и вычисление среднего значения для каждого столбца

In [1]:
import numpy as np

In [2]:
a = (np.array([[1, 2, 3, 3, 1], [6, 8, 11, 10, 7]])).transpose()

In [3]:
a

array([[ 1,  6],
       [ 2,  8],
       [ 3, 11],
       [ 3, 10],
       [ 1,  7]])

In [4]:
mean_a = a.mean(axis=0)

In [5]:
mean_a

array([2. , 8.4])

### Задание 2-n
Вычисление массива, "отцентрированного" по среднему значению признака (столбца).

In [6]:
a_centered = a - mean_a
a_centered

array([[-1. , -2.4],
       [ 0. , -0.4],
       [ 1. ,  2.6],
       [ 1. ,  1.6],
       [-1. , -1.4]])

### Задание 3-n
Скалярное произведение столбцов массива a_centered. Вычисление ковариации двух признаков (столбцов).

In [7]:
a_centered_sp = (a_centered[:, 0]).dot(a_centered[:, 1])
a_centered_sp

8.0

In [8]:
covar = a_centered_sp / (a_centered.shape[0] - 1)
covar

2.0

### Задание 4-n
Вычисление ковариационной матрицы.

In [9]:
covar_mat = np.cov(a.transpose())
covar_mat

array([[1. , 2. ],
       [2. , 4.3]])

In [10]:
print("Ковариация признаков: {}".format(covar_mat[1, 0]))

Ковариация признаков: 2.0


## Вычисления с помощью Pundas



### Задание 1-p
Создание книжных датафреймов

In [11]:
import pandas as pd

In [12]:
authors = pd.DataFrame(
    {
        "author_id": [1, 2, 3],
        "author_name": ['Тургенев', 'Чехов', 'Островский']
    }
)
authors

author_id author_name
0          1    Тургенев
1          2       Чехов
2          3  Островский

In [13]:
book = pd.DataFrame(
    {
        "author_id": [1, 1, 1, 2, 2, 3, 3],
        "book_title": ['Отцы и дети', 'Рудин', 'Дворянское гнездо', 'Толстый и тонкий', 'Дама с собачкой', 'Гроза', 'Таланты и поклонники'],
        "price": [450, 300, 350, 500, 450, 370, 290]
    }
)
book

author_id            book_title  price
0          1           Отцы и дети    450
1          1                 Рудин    300
2          1     Дворянское гнездо    350
3          2      Толстый и тонкий    500
4          2       Дама с собачкой    450
5          3                 Гроза    370
6          3  Таланты и поклонники    290

### Задание 2-p
Объединение книжных DataFram-ов

In [14]:
authors_price = pd.merge(authors, book, on='author_id', how='outer')
authors_price

author_id author_name            book_title  price
0          1    Тургенев           Отцы и дети    450
1          1    Тургенев                 Рудин    300
2          1    Тургенев     Дворянское гнездо    350
3          2       Чехов      Толстый и тонкий    500
4          2       Чехов       Дама с собачкой    450
5          3  Островский                 Гроза    370
6          3  Островский  Таланты и поклонники    290

### Задание 3-p
5-ть самых дорогих книг

In [15]:
top5 = authors_price.nlargest(5, 'price')
top5

author_id author_name         book_title  price
3          2       Чехов   Толстый и тонкий    500
0          1    Тургенев        Отцы и дети    450
4          2       Чехов    Дама с собачкой    450
5          3  Островский              Гроза    370
2          1    Тургенев  Дворянское гнездо    350

### Задание 4-p
Статистика

In [16]:
authors_stat = authors_price['author_name'].unique()

In [17]:
authors_price.groupby['author_name']

TypeError: 'method' object is not subscriptable

In [ ]:
authors_stat['price_min'] = authors_price.groupby['author_name'].authors_price.groupby['price'].min()